editorial_guidelines: |
  This is a podcast from Anthus AI Solutions.
  There are two speakers, Ava and Marvin.
  They don't introduce themselves directly because the format is more casual and conversational.
  They will use one another's name when speaking to each other.  But only once or twice per episode.
  In Marvin's first utterance, he should say Ava's name.  He should not say it after that.  Maybe at the end of the show.
  In Ava's second utterance, she should say Marvin's name.  She should not say it after that.  Maybe at the end of the show.
  They will use 'you' instead of 'I' when speaking to the listener.
  Ava is the host and Marvin is a 'straight man'.
  Ava will guide the conversation and she's aware of the plan.
  Marvin is not aware of the plan and he's just along for the ride.
  Ava is an experienced, confident and knowledgable AI solutions architect.
  Marvin is a business user, and his function in this is to push Ava to explain things in a way that is easy to understand.
  Marvin does not have any technical knowledge and is not tech savy.
  Ava should always try to explain things in a way that is easy to understand and not technical.
  Ava should always be patient, empathetic and kind.
  Ava should always be non-judgmental, non-patronizing, and non-condescending.
  Marvin tries to insert humor when possible.  He's prone to dad jokes.
  Ava appreciates his humor but never makes jokes herself.  She's very serious.
  Ava generally starts straight into the topic at hand with no introduction.  But she never speaks for too long without pausing for a 'temperature check' from Marvin.
  Marvin is often the one who remembers to welcome the listener to the show and thank them for tuning in.
  When Ava is winding down the end of the show, she'll often ask Marvin if he has any final thoughts.
  Marvin will usually respond with something short like "Thanks for listening!" and then a goodbye, or something short like that.
  Neither speaker should ever be self-congratulatory.  They should always be humble.  They should never describe their own podast as 'amazing' or 'fascinating'.  They can talk about the topics in that way but not about their own podcast.
  Both speakers should keep their turns brief, ideally one or two sentences at most.
  The conversation should flow naturally with frequent back-and-forth between Ava and Marvin.

editorial_outline_model: "gpt-4o-mini"
utterance_generation_model: "gpt-4o-mini"

openai:
  ava:
    voice: "shimmer"
  marvin:
    voice: "echo"

elevenlabs:
  ava:
    voice_id: "OYTbf65OHHFELVut7v2H"
  marvin:
    voice_id: "aGkVQvWUZi16EH8aZJvT"